name: flutterprojet
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # HTTP client & API handling
  dio: ^5.4.0
  retrofit: ^4.4.2
  json_serializable: ^6.7.1

  # Gestion d'état
  provider: ^6.1.2

  # Affichage de cartes interactives
  google_maps_flutter: ^2.5.0

  # Mode sombre & préférences utilisateur
  shared_preferences: ^2.2.3

  # Animation & UI avancée
  flutter_animate: ^4.5.0
  lottie: ^2.7.0

  # Gestion des icônes et UI moderne
  font_awesome_flutter: ^10.7.0

  # Localisation & formatage de dates
  intl: ^0.20.2

  # Gestion des permissions (si besoin pour la localisation)
  permission_handler: ^11.3.0
  json_annotation: ^4.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  retrofit_generator: ^8.1.0
  build_runner: ^2.4.7

flutter:
  uses-material-design: true

  assets:
    - assets/city.list.json
    - assets/images/
#    - assets/animations/

